"""eMMC, JEDEC 153-ball FBGA — generic "eMMC_BGA153" + derived "KLMBG2JETD-B041" (one generator).

FACTS (D12): facts/emmc-truth-153.json = ball -> vendor name, parsed from Kingston eMMC TB29
(PZ90) v1.1, "Table 8 - Ball Assignment, Top View (HS400)" (doc page 13; `pdftotext -layout`
lines 362-410). Pin descriptions + types: same doc pages 9-10 (lines 275-330): DAT[7:0] I/O/PP,
CMD I/O/PP/OD, CLK I, DS O ("generated by the device"), RST_n I, Vcc/Vccq/Vss/Vssq S, Vddi
"not a power supply input ... external Creg capacitor", RFU/VSF/NC "not internally connected"
(NC balls may be routed through). Cross-checked against Samsung KLMAG1JETD-B041 s3.1 Table 2
(same B041-family ballout; Samsung merges Vssq into VSS, names RST_n "RSTN"). Pad set = the
authored footprint EMMC_BGA153 = facts/emmc-153-ball-positions.json; the generator ASSERTS the
symbol's 153 pin numbers are exactly that set.

Units (review verify/symbols-0824/review/emmc.md, winner V3, pitch 3.81 = D8):
  1 "eMMC I/F"        DAT / CMD/CLK / STROBE / RESET left; Vcc x4 / Vccq x5 / Vddi right.
                      Vendor DUPLICATE names (Vcc, Vccq) — never invented indices; captions are
                      the vendor rail names, never a board voltage (Vccq is 1.8 V OR 3.3 V).
  2 "eMMC Vss/Vssq"   11 grounds, ONE uncaptioned left column (D9: pure GND column, no captions;
                      the vendor names Vss/Vssq are on every pin and the title carries the domain).
  3 "eMMC NC 1/3"     40 NC balls, 20 left + 20 right, row-major (D10: every pad gets a pin).
  4 "eMMC NC 2/3"     next 40 NC balls.
  5 "eMMC RFU/VSF/NC" 7 RFU + 6 VSF (captioned) + the last 27 NC. 40 + 40 + 40 = 120 = 153 - 33.
Etypes (D11/docs/02): DAT/CMD bidirectional, CLK input, DS output, RST_n input, Vcc/Vccq/Vss/Vssq
power_in, Vddi passive, NC/RFU/VSF no_connect. Board roles (EMMC_D0..) are net labels at the
instance (boardlib/sheets/storage.py), keyed by ball number from pindata.EMMC_PINS.
"""
from symlib.common import *  # noqa: F401,F403
from symlib.common import _FPLIB, _HERE, _json, _props

GENERIC = "eMMC_BGA153"
MPN = "KLMBG2JETD-B041"
LCSC = "C2803245"
DS_KINGSTON = "Kingston-EMMC-TB29-PZ90-v1.1.pdf"   # JEDEC 153-ball truth (Table 8 + pin table)
DS_SAMSUNG = "KLMAG1JETD-B041-UUGear.pdf"           # Samsung B041-family ballout cross-check

_TRUTH = _json.load(open(_HERE / "facts/emmc-truth-153.json"))
_BALLS = _json.load(open(_HERE / "facts/emmc-153-ball-positions.json"))
assert set(_TRUTH) == set(_BALLS) and len(_BALLS) == 153, \
    f"eMMC truth ({len(_TRUTH)}) vs footprint pad set ({len(_BALLS)}) disagree"


def _natkey(ball):
    return (ball[0], int(ball[1:]))


def _balls(name):
    """Balls carrying vendor `name`, row-major (A1, A2, ... P14)."""
    return sorted((b for b, n in _TRUTH.items() if n == name), key=_natkey)


def _pins(name, balls, etype):
    return [(name, b, etype) for b in balls]


def _pins_named(balls, etype):
    return [(_TRUTH[b], b, etype) for b in balls]


# unique-name balls (DAT0..7, CMD, CLK, DS, RST_n, Vddi) -> ball
_TRUTH_INV = {n: b for b, n in _TRUTH.items()
              if n not in ("NC", "RFU", "VSF", "Vcc", "Vccq", "Vss", "Vssq")}


def _units():
    dat = [_TRUTH_INV[f"DAT{i}"] for i in range(8)]
    u_if = Unit(
        "eMMC I/F",
        left=[Group("DAT", _pins_named(dat, "bidirectional")),
              Group("CMD/CLK", [("CMD", _TRUTH_INV["CMD"], "bidirectional"),
                                ("CLK", _TRUTH_INV["CLK"], "input")]),
              Group("STROBE", [("DS", _TRUTH_INV["DS"], "output")]),
              Group("RESET", [("RST_n", _TRUTH_INV["RST_n"], "input")])],
        right=[Group("Vcc", _pins("Vcc", _balls("Vcc"), "power_in")),
               Group("Vccq", _pins("Vccq", _balls("Vccq"), "power_in")),
               Group("Vddi", _pins("Vddi", _balls("Vddi"), "passive"))],
        width=35.56)   # from pin ink (5+4 chars); the 50.8 floor left ~30 mm of dead interior
    # unit 2 — GND: one uncaptioned column, Vss then Vssq (D9). Vendor names ARE the caption.
    u_gnd = Unit(
        "eMMC Vss/Vssq",
        left=[Group("", _pins("Vss", _balls("Vss"), "power_in")
                    + _pins("Vssq", _balls("Vssq"), "power_in"))],
        width=22.86)   # left-only column; the 38.1 floor was half dead space
    nc, rfu, vsf = _balls("NC"), _balls("RFU"), _balls("VSF")
    assert (len(nc), len(rfu), len(vsf)) == (107, 7, 6), (len(nc), len(rfu), len(vsf))
    u_nc1 = Unit("eMMC NC 1/3",
                 left=[Group("NC", _pins("NC", nc[0:20], "no_connect"))],
                 right=[Group("NC", _pins("NC", nc[20:40], "no_connect"))], width=25.4)
    u_nc2 = Unit("eMMC NC 2/3",
                 left=[Group("NC", _pins("NC", nc[40:60], "no_connect"))],
                 right=[Group("NC", _pins("NC", nc[60:80], "no_connect"))], width=25.4)
    u_nc3 = Unit("eMMC RFU/VSF/NC",
                 left=[Group("RFU", _pins("RFU", rfu, "no_connect")),
                       Group("VSF", _pins("VSF", vsf, "no_connect")),
                       Group("NC", _pins("NC", nc[80:86], "no_connect"))],
                 right=[Group("NC", _pins("NC", nc[86:107], "no_connect"))], width=25.4)
    units = [u_if, u_gnd, u_nc1, u_nc2, u_nc3]
    # D10/PADCOV: every pad of the footprint is a pin, once, under its vendor name.
    seen = {}
    for u in units:
        for side in (u.left, u.right, u.bottom):
            for g in side:
                for name, num, _et in g.pins:
                    assert num not in seen, f"eMMC ball {num} authored twice"
                    assert _TRUTH[num] == name, f"eMMC {num}: authored {name!r} != DS {_TRUTH[num]!r}"
                    seen[num] = name
    assert set(seen) == set(_BALLS) and len(seen) == 153, \
        f"eMMC symbol pins {len(seen)} != footprint pads {len(_BALLS)}"
    return units


def emmc_generic():
    """Generic JEDEC 153-ball eMMC (any vendor; the library part). Value = its own name."""
    return author_symbol(GENERIC, _units(),
                         props=[("Reference", "U", False), ("Value", GENERIC, False),
                                ("Footprint", f"{_FPLIB}:EMMC_BGA153", True),
                                ("Datasheet", DS_KINGSTON, True)],
                         pitch=3.81)


def emmc():
    """Samsung KLMBG2JETD-B041 (32 GB eMMC 5.1) — the fitted part hydra places (D13). Emits the
    generic eMMC_BGA153 into the same authored lib first (same units, same generator)."""
    emmc_generic()
    return author_symbol(MPN, _units(),
                         props=_props("U", MPN, MPN, LCSC, fp=f"{_FPLIB}:EMMC_BGA153",
                                      ds=DS_SAMSUNG),
                         pitch=3.81)


def emmc_nc_balls(sym):
    """{unit: (ball, ...)} for the no_connect units of an authored eMMC symbol — the sheet X's
    every one (docs/02: nc= only references pins that exist; read them from the symbol)."""
    return {u: tuple(num for num, _n in sym.pin_table(u)) for u in (3, 4, 5)}


__all__ = [_n for _n in dict(globals()) if not _n.startswith("__")]
